### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by nvanalfen** [nvanalfen/halotools_ia#1]
Here's a list of tasks left to do in order to complete the paper and make the code more usable. Feel free to add or remove any as needed.

Paper tasks:
- [x] Write Intro
- [x] Sections 2.3.1 and 2.3.2, decide if these headings are necessary
- [x] Section 4
    - [x] 4.1 Naive radial misalignment
        - [x] Replace chi^2 values with % error values
        - [x] Discuss why we also looked at a fit to the 1-Halo regime (a rough starting paragraph already exists for this)
        - [x] Discuss why we fit cen-sat
    - [x] 4.2 Satellite Anisotropy
        - [x] Discuss that the only difference (in the plot shown) is the isotropy of the halos
        - [x] Place in % error values for comparison of models
    - [x] 4.3 Capturing Subhalo IA in Gravity Only simulations
        - [x] Insert three-panel plot showing xi, omega, and eta (Like the Illustris plot later) but compare subhalos, radially dependent alignment strength, and constant alignment strength
        - [x] We can recreate something somewhat realistic* (* in the 1-H regime)
        - [x] Insert values for % difference
- [ ] Section 5
    - [x] Opening
        - [x] Discuss that we are now fitting central alignment strength and satellite alignment strength (still using the radial alignment model)
    - [x] 5.2 Misalignment
        - [x] Show three-panel plot (the parameter space plot from emcee and corner, one for each of the samples matching the Illustris mass thresholds)
    - [ ] 5.3 Reproducing Galaxy Orientation Correlation Functions
        - [x] Wrap up what this section has been doing and tie results together
        - [ ] Deal with weird xi chi^2 issue
- [x] Section 6 - Future directions: Bayesian inference of IA
    - [x] Cut (unless we feel a compelling reason to add a paragraph about how this can be future work)
- [x] Section 7 - Conclusions (Now Section 6 after cutting old section 6)
    - [x] Radial dependence helps align galaxies in the 1-H regime even if no halo orientation is available (use % error)
    - [x] Discuss how the central and satellite alignments could be adjusted to be comparable to Illustris
    - [x] Discuss that our models seem to work in 1-H, but there seems to be more environmental information needed to accurately model correlations in 2-H
    - [x] Other?
- [ ] General
    - [ ] Are figures 9 and 11 referring to the same thing? (no longer those numbers. "central and satellite galaxy alignments" showing two sets of three points, and "corner plot of central and satellite alignment posteriors by fitting
EE and ED." showing a sin)

--------------------------------------------------------------------------------------------------------------------------------------------------

Code Tasks:
- [ ] intrinsic_alignments repo (requires Duncan's alignments_devel branch of halotools, rather than the current version of halotools)
    - [ ] Make it compatible with current halotools
- [ ] rotations repo (I linked it to my fork of rotations which required one minor change)
    - [ ] Change all calls to rotations into calls to the rotations utils in halotools (and make sure it still works)

**Comment by c-d-leonard** [comment]
Looks good! A couple small questions:
- Section 4.3: I'm not sure I have a good understanding of what is going to go here - is this going to basically sum up what you can do with what is developed in Section 4.1 and 4.2?
- I would personally say there is sufficient material here without Section 6 (Bayesian inference) and I'd suggest deferring that to future work.

**Comment by nvanalfen** [comment]
On section 4.3, to my understanding, yes. Maybe he had some other intention for it, but reading over everything, it feels like it's just restating everything we've already done up until that point. Whatever the original plan was, I think it would be a good spot to just summarize the results of 4.1 and 4.2 and look at things as a whole.
